junit: 4.8.2

gems:
  #- ci_reporter
  - buildr >= 1.4.3
  - buildr-iidea = 0.0.10

artifacts:
  javancss: org.codehaus.javancss:javancss:jar:32.53
  jhbasic: javancss:jhbasic:jar:29.50
  ccl: javancss:ccl:jar:29.50
  intellij_annotations: com.intellij:annotations:jar:9.0.3
  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javaee_api: javax:javaee-api:jar:6.0

repositories:
  remote:
   - http://www.ibiblio.org/maven2
  release_to:
    url: sftp://www.stocksoftware.com.au/www/stocksoftware/web/repositories/releases
    permissions: 0664
