repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_jsr305: com.google.code.findbugs:jsr305:jar:3.0.0
  findbugs_annotations: com.google.code.findbugs:annotations:jar:3.0.0
  javaee_api: javax:javaee-api:jar:7.0
