repositories:
  remote:
   - http://repo.fire.dse.vic.gov.au/content/groups/fisg
   - http://repo1.maven.org/maven2
   - http://download.eclipse.org/rt/eclipselink/maven.repo
   - http://repository.codehaus.org

artifacts:
  eclipselink: org.eclipse.persistence:eclipselink:jar:2.3.0
  postgresql: postgresql:postgresql:jar:9.1-901.jdbc4
  postgis_jdbc: org.postgis:postgis-jdbc:jar:1.3.3
  jtds: net.sourceforge.jtds:jtds:jar:1.2.4
  javaee_api: javax:javaee-api:jar:7.0
  javax_annotation: com.google.code.findbugs:jsr305:jar:2.0.1
  json: org.json:json:jar:20090211
  jackson_core: org.codehaus.jackson:jackson-core-asl:jar:1.9.4
  jackson_mapper: org.codehaus.jackson:jackson-mapper-asl:jar:1.9.4
  javax_el: org.glassfish:javax.el:jar:3.0.0

  atmosphere_annotations: org.atmosphere:atmosphere-annotations:jar:1.0.1
  atmosphere_jquery: org.atmosphere:atmosphere-jquery:war:1.0.1
  atmosphere_runtime: org.atmosphere:atmosphere-runtime:jar:1.0.1

  atmosphere_compat_tomcat: org.atmosphere:atmosphere-compat-tomcat:jar:1.0.1
  atmosphere_compat_tomcat7: org.atmosphere:atmosphere-compat-tomcat7:jar:1.0.1
  atmosphere_compat_jbossweb: org.atmosphere:atmosphere-compat-jbossweb:jar:1.0.1

  slf4j_api: org.slf4j:slf4j-api:jar:1.6.6
  slf4j_jdk14: org.slf4j:slf4j-jdk14:jar:1.6.6
  infomas_annotation_detector: eu.infomas:annotation-detector:jar:3.0.0

  geolatte_common: org.geolatte:geolatte-common:jar:0.5

  gwt_user: com.google.gwt:gwt-user:jar:2.5.1
  gwt_dev: com.google.gwt:gwt-dev:jar:2.5.1
  gwt_gin: com.google.gwt.inject:gin:jar:2.0.0
  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javax_validation_sources: javax.validation:validation-api:jar:sources:1.0.0.GA
  restygwt: org.fusesource.restygwt:restygwt:jar:1.3.1

  geolatte_geom: org.geolatte:geolatte-geom:jar:0.12-rf
  jts: com.vividsolutions:jts:jar:1.10

  geolatte_geom_eclipselink: org.realityforge.jeo.geolatte.jpa.eclipselink:geolatte-geom-eclipselink:jar:0.2
  replicant: org.realityforge:replicant:jar:0.4.8-8-g97e2168
  replicant_sources: org.realityforge:replicant:jar:sources:0.4.8-8-g97e2168

  google_guice: com.google.inject:guice:jar:3.0
  google_guice_assistedinject: com.google.inject.extensions:guice-assistedinject:jar:3.0
  aopalliance: aopalliance:aopalliance:jar:1.0 # Required for guice

  # Mocking library used to mock out UI in planner application
  mockito: org.mockito:mockito-all:jar:1.8.5
