<% user_code = ENV['USER'] %>
<% prefix = "#{user_code}_" %>
devhost: &devhost
  appname: <%= user_code %>
  username: stock-dev
  password: letmein
  host: vw-firesql-104
  instance: mssql01
  force_drop: true
  reindex_on_import: true
  shrink_on_import: false
  no_create: false

development:
  database: <%= prefix %>FOOTPRINTS_DEV
  <<: *devhost

test:
  database: <%= prefix %>FOOTPRINTS_TES
  <<: *devhost

import:
  database: PROD_CLONE_FOOTPRINTS
  <<: *devhost
