<% user_code = ENV['USER'] %>
<% prefix = "#{user_code}_" %>
devhost: &devhost
  username: <%= user_code %>
  #username: stock-dev
  password: letmein
  host: vw-firesql-104
  instance: mssql01
  force_drop: true

development:
  database: <%= prefix %>FOOTPRINTS_DEV
  <<: *devhost

test:
  database: <%= prefix %>FOOTPRINTS_TEST
  <<: *devhost

import:
  database: PROD_CLONE_FOOTPRINTS
  <<: *devhost
