<% user_code = "MYUSER" %>
<% prefix = "#{user_code}_" %>
devhost: &devhost
  adapter: mssql
  appname: <%= user_code %>
  username: stock-dev
  password: letmein
  timeout: 50000
  host: vw-firesql-104
  instance: mssql01
  force_drop: true
  no_create: false

msdb:
  database: msdb
  <<: *devhost

development:
  database: <%= prefix %>FOOTPRINTS_DEV
  <<: *devhost

test:
  database: <%= prefix %>FOOTPRINTS_TES
  <<: *devhost

import:
  database: <%= prefix %>FOOTPRINTS_DEV
  <<: *devhost

